
package com.appspot.stingion.controller.minor.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SimpleSoapService", targetNamespace = "http://soap.minor.controller.stingion.appspot.com/", wsdlLocation = "http://62.205.136.149:8082/mainside/hello?wsdl")
public class SimpleSoapService
    extends Service
{

    private final static URL SIMPLESOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIMPLESOAPSERVICE_EXCEPTION;
    private final static QName SIMPLESOAPSERVICE_QNAME = new QName("http://soap.minor.controller.stingion.appspot.com/", "SimpleSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://62.205.136.149:8082/mainside/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIMPLESOAPSERVICE_WSDL_LOCATION = url;
        SIMPLESOAPSERVICE_EXCEPTION = e;
    }

    public SimpleSoapService() {
        super(__getWsdlLocation(), SIMPLESOAPSERVICE_QNAME);
    }

    public SimpleSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIMPLESOAPSERVICE_QNAME, features);
    }

    public SimpleSoapService(URL wsdlLocation) {
        super(wsdlLocation, SIMPLESOAPSERVICE_QNAME);
    }

    public SimpleSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIMPLESOAPSERVICE_QNAME, features);
    }

    public SimpleSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SimpleSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SimpleSoap
     */
    @WebEndpoint(name = "SimpleSoapPort")
    public SimpleSoap getSimpleSoapPort() {
        return super.getPort(new QName("http://soap.minor.controller.stingion.appspot.com/", "SimpleSoapPort"), SimpleSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SimpleSoap
     */
    @WebEndpoint(name = "SimpleSoapPort")
    public SimpleSoap getSimpleSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.minor.controller.stingion.appspot.com/", "SimpleSoapPort"), SimpleSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIMPLESOAPSERVICE_EXCEPTION!= null) {
            throw SIMPLESOAPSERVICE_EXCEPTION;
        }
        return SIMPLESOAPSERVICE_WSDL_LOCATION;
    }

}
