
package com.appspot.stingion.controller.minor.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SimpleSoap", targetNamespace = "http://soap.minor.controller.stingion.appspot.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SimpleSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getIt", targetNamespace = "http://soap.minor.controller.stingion.appspot.com/", className = "com.appspot.stingion.controller.minor.soap.GetIt")
    @ResponseWrapper(localName = "getItResponse", targetNamespace = "http://soap.minor.controller.stingion.appspot.com/", className = "com.appspot.stingion.controller.minor.soap.GetItResponse")
    @Action(input = "http://soap.minor.controller.stingion.appspot.com/SimpleSoap/getItRequest", output = "http://soap.minor.controller.stingion.appspot.com/SimpleSoap/getItResponse")
    public String getIt(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
